name: Create Dev to Main PR
on:
  schedule:
    - cron: '* * * * *' # Runs every min
  workflow_dispatch: # Allows manual triggering

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev # Checkout the dev branch
          fetch-depth: 0 # Fetch full history for branching

      - name: Get today's date
        id: date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create new branch from dev
        run: |
          git checkout dev
          git branch -D gha/dev-to-main || true # Delete branch if it exists
          git checkout -b gha/dev-to-main
          echo "${{ env.TODAY }}" >> foo.txt
          git add foo.txt
          git commit -m "chore: update foo.txt with date ${{ env.TODAY }}"

      - name: Push new branch
        run: git push origin gha/dev-to-main --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: merge dev into main'
          title: 'Merge dev into main - ${{ env.TODAY }}'
          body: |
            This PR merges the latest changes from `dev` into `main`.
            Automatically created on ${{ env.TODAY }} by GitHub Actions.
          branch: gha/dev-to-main
          base: main
          delete-branch: false
