name: Create Dev to Main PR
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev # Checkout the dev branch

      - name: Get today's date
        id: date
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Update a file
        run: |
          echo "${{ env.TODAY }}" >> foo.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: merge dev into main'
          title: 'Merge dev into main - ${{ env.TODAY }}'
          body: |
            This PR merges the latest changes from `dev` into `main`.
            Automatically created on ${{ env.TODAY }} by GitHub Actions.
          branch: gha/dev-to-main
          base: main
          delete-branch: false
